/**
 * Builds the browser bundles served by src/hosted/hosted-assets.ts.
 *
 *   node --experimental-strip-types --disable-warning=ExperimentalWarning scripts/build-client.ts
 *   node ... scripts/build-client.ts --check   (exit 1 when the committed bundle is stale)
 *
 * No bundler: each module is type-stripped with node:module and concatenated into one IIFE.
 * Imports and `export` keywords are removed structurally; modules therefore share one scope and
 * the build fails on duplicate top-level names. Output: src/hosted/client-bundle.ts (committed).
 */
import { readFileSync, writeFileSync } from "node:fs";
import { stripTypeScriptTypes } from "node:module";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const ROOT = join(dirname(fileURLToPath(import.meta.url)), "..");
const OUT = join(ROOT, "src/hosted/client-bundle.ts");

/** Order matters only for top-level `const` used at load time; functions hoist. */
export const CLIENT_BUNDLES: Record<string, string[]> = {
  CONSOLE_BUNDLE_JS: [
    "src/hosted/store-form-fields.ts",
    "src/hosted/providers/registry.ts",
    "src/hosted/providers/connect-redirect.ts",
    "src/hosted/client/shared.ts",
    "src/hosted/client/routes.ts",
    "src/hosted/client/activity.ts",
    "src/hosted/client/store-form.ts",
    "src/hosted/client/inbox.ts",
    "src/hosted/client/credentials.ts",
    "src/hosted/client/access.ts",
    "src/hosted/client/account.ts",
    "src/hosted/client/team.ts",
    "src/hosted/client/console.ts",
  ],
  COLLECT_BUNDLE_JS: [
    "src/hosted/store-form-fields.ts",
    "src/hosted/providers/connect-redirect.ts",
    "src/hosted/client/shared.ts",
    "src/hosted/client/store-form.ts",
    "src/hosted/client/collect.ts",
  ],
};

const IMPORT_RE = /^import\s[\s\S]*?from\s+"[^"]+";[ \t]*$/gm;
const SIDE_EFFECT_IMPORT_RE = /^import\s+"[^"]+";[ \t]*$/gm;
const REEXPORT_RE = /^export\s*\{[^}]*\}(?:\s*from\s+"[^"]+")?;[ \t]*$/gm;
const REFERENCE_RE = /^\/\/\/\s*<reference\b.*$/gm;
const EXPORT_DECL_RE = /^export\s+(?=(?:async\s+)?(?:const|let|var|function|class)\b)/gm;
const TOP_LEVEL_DECL_RE = /^(?:async\s+)?(?:const|let|var|function|class)\s+([A-Za-z_$][\w$]*)/gm;

/** One module as plain browser JS: no types, no imports, no export keywords. */
export function moduleToScript(source: string): string {
  const stripped = stripTypeScriptTypes(source, { mode: "strip" });
  return stripped
    .replace(REFERENCE_RE, "")
    .replace(IMPORT_RE, "")
    .replace(SIDE_EFFECT_IMPORT_RE, "")
    .replace(REEXPORT_RE, "")
    .replace(EXPORT_DECL_RE, "")
    .split("\n")
    .map((line) => line.replace(/\s+$/, ""))
    .join("\n")
    .replace(/\n{3,}/g, "\n\n")
    .trim();
}

export function topLevelNames(script: string): string[] {
  const names: string[] = [];
  for (const m of script.matchAll(TOP_LEVEL_DECL_RE)) if (m[1]) names.push(m[1]);
  return names;
}

export function buildBundle(files: string[], root: string = ROOT): string {
  const seen = new Map<string, string>();
  const parts: string[] = [];
  for (const file of files) {
    const script = moduleToScript(readFileSync(join(root, file), "utf8"));
    for (const name of topLevelNames(script)) {
      const prior = seen.get(name);
      if (prior) throw new Error(`Duplicate top-level name "${name}" in ${file} (already declared in ${prior})`);
      seen.set(name, file);
    }
    parts.push(`// ---- ${file} ----\n${script}`);
  }
  return `"use strict";\n(() => {\n${parts.join("\n\n")}\n})();\n`;
}

function asTemplateLiteral(js: string): string {
  return "`" + js.replace(/\\/g, "\\\\").replace(/`/g, "\\`").replace(/\$\{/g, "\\${") + "`";
}

export function renderBundleModule(bundles: Record<string, string[]> = CLIENT_BUNDLES, root: string = ROOT): string {
  const header = [
    "/**",
    " * GENERATED by scripts/build-client.ts from src/hosted/client/*.ts. Do not edit by hand.",
    " * Regenerate: node --experimental-strip-types --disable-warning=ExperimentalWarning scripts/build-client.ts",
    " * test/client-bundle.test.ts fails when this file is stale.",
    " */",
    "",
  ];
  const body = Object.entries(bundles).map(([name, files]) => {
    const list = files.map((f) => ` *   ${f}`).join("\n");
    return `/** Bundle of:\n${list}\n */\nexport const ${name} = ${asTemplateLiteral(buildBundle(files, root))};\n`;
  });
  return header.join("\n") + body.join("\n");
}

function main(argv: string[]): void {
  const next = renderBundleModule();
  if (argv.includes("--check")) {
    let current: string;
    try {
      current = readFileSync(OUT, "utf8");
    } catch {
      current = "";
    }
    if (current !== next) {
      console.error(`${relative(ROOT, OUT)} is stale. Run scripts/build-client.ts and commit the result.`);
      process.exit(1);
    }
    console.log(`${relative(ROOT, OUT)} is current.`);
    return;
  }
  writeFileSync(OUT, next);
  console.log(`wrote ${relative(ROOT, OUT)} (${next.length} bytes)`);
}

if (process.argv[1] && fileURLToPath(import.meta.url) === process.argv[1]) main(process.argv.slice(2));
